// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-defined note type, declared under `[note_types.<name>]`.
 *
 * Schema-only by design: the reconciler already stores `type` as an opaque
 * string, so a custom type indexes, searches, and accrues backlinks like any
 * note. What this declares is the *rules* — folder, field requirements, a
 * template, ordering — that lint and normalise enforce. It carries no
 * behaviour: caps, lifecycle, and cross-type aggregation remain exclusive to
 * the built-in types (they go through typed frontmatter structs a config type
 * never satisfies).
 *
 * This struct holds only what `cdno-core` can validate *structurally* (no
 * knowledge of the built-in type names lives here); the reserved-name check
 * against the built-in `NoteType` set is `cdno-domain`'s job.
 */
export type CustomNoteType = { 
/**
 * Vault-relative folder its notes live in, e.g. `"people"`.
 */
folder: string, 
/**
 * Frontmatter fields that must be present and non-null — lint errors on a
 * note of this type that omits one.
 */
required: Array<string>, 
/**
 * Frontmatter fields that may be present; included in the canonical
 * frontmatter order after the required ones.
 */
optional: Array<string>, 
/**
 * Template filename under `.cuaderno/templates/`. Defaults to `<name>.md`
 * when omitted (resolved at create time, not here).
 */
template: string | null, 
/**
 * Whether notes of this type are append-only. Accepted and exposed now;
 * lint enforcement is deferred (no archival-snapshot machinery exists
 * outside actions yet).
 */
append_only: boolean, 
/**
 * Frontmatter field to draw the note's display title from. When omitted,
 * the title comes from the body's first `# H1` (matching built-in notes).
 */
title_field: string | null, 
/**
 * Frontmatter field carrying the note's date, used by date-filtered
 * search. When omitted, the type has no logical date.
 */
date_field: string | null, };
