// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldSpec } from "./FieldSpec";

/**
 * Per-type schema extension: `[schemas.<type>]`.
 *
 * Adds vault-specific required fields on top of the built-in ones — either as
 * a bare name list (`extra_required`, lint-only) or as typed field specs
 * (`[schemas.<type>.fields.<name>]`, `#301`).
 */
export type SchemaExtension = { 
/**
 * Bare extra-required field names. Retained for backward compatibility:
 * lint-only and built-in-only, never a create-time error. Desugared into
 * the [`SchemaExtension::declared_fields`] view as untyped, non-required
 * string fields.
 */
extra_required: Array<string>, 
/**
 * Typed field declarations, keyed by field name (`#301`).
 */
fields: { [key in string]: FieldSpec }, };
