// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachedAction } from "./AttachedAction";
import type { EnergyLevel } from "./EnergyLevel";

/**
 * One open action bullet from a project's `## Next Actions` section,
 * produced by [`Vault::list_actions`]. Closed (`- [x]`) bullets are
 * not part of the action surface — action completion removes the
 * bullet rather than checking it — so the list only carries open
 * items.
 */
export type ActionListEntry = { 
/**
 * The bullet text after `- [ ] `, including any `(<energy>)`
 * suffix and wikilink target. Preserved verbatim so the caller
 * can render or re-match against it without re-parsing structure.
 */
text: string, 
/**
 * Energy bucket parsed from the trailing `(deep|medium|light)`
 * suffix; `None` when the bullet has no recognised suffix.
 */
energy: EnergyLevel | null, 
/**
 * `Some` when the bullet wikilinks an action note (`[[actions/
 * <slug>]]`) **and** that note still exists. A wikilink whose
 * note is missing surfaces as `None` (the bullet text still
 * carries the wikilink, signalling drift).
 */
attached: AttachedAction | null, };
