// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of an action note. Created `Active`; flipped to
 * `Completed` by `Vault::complete_action` in the same transaction
 * that removes the matching bullet from the project map and moves
 * the file to `actions/_done/<year>/`. `Blocked` is set explicitly
 * when external work is gating progress; the `blocker` frontmatter
 * field carries the human description.
 */
export type ActionStatus = "active" | "completed" | "blocked";
