// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a metric's values collapse to one point per date (`#483`).
 *
 * The correctness fix at the heart of `#478`: every tracked quantity has a
 * kind, and the kind decides the reduction. Summing is right for a total and
 * wrong for everything else — it adds successive readings of a balance, and
 * it grows a rating with how often you record it.
 *
 * There is no `Count`. It would reduce record *presence* rather than a
 * field's values, unlike every other arm, and the occurrence activity it
 * would serve declares no metrics at all.
 */
export type Aggregate = "sum" | "last" | "max" | "min" | "mean";
