// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionStatus } from "./ActionStatus";

/**
 * The action note hanging off a wikilink bullet. Carries the slug
 * and the current frontmatter `status` so a list view can flag
 * active / blocked / completed inline.
 */
export type AttachedAction = { slug: string, status: ActionStatus, };
