// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One backlinking note: where it is, and what to call it.
 *
 * A raw vault path is a poor label, so the title travels alongside it —
 * but the index's `title` is the *frontmatter* field, and most RLM note
 * types carry their name in the body H1 instead (the H1 feeds the search
 * row, not this one). So `title` is absent more often than not, and the
 * frontend derives a readable label from the filename in that case.
 * Reading each source's H1 here would mean a file read per backlink on
 * every load of the page.
 */
export type BacklinkRow = { path: string, 
/**
 * The source note's frontmatter `title`, absent for the many note
 * types that don't declare one — the frontend then derives a label
 * from the filename.
 */
title: string | null, };
