// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backlinks to the project, grouped by source note type, as path
 * strings ready for the frontend to render and route on. Mirrors the
 * domain `ProjectBacklinks` grouping (which holds `VaultPath`s and
 * carries no ts-rs derives).
 */
export type BacklinksView = { portfolios: Array<string>, questions: Array<string>, evidence: Array<string>, actions: Array<string>, other: Array<string>, };
