// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacklinkRow } from "./BacklinkRow";

/**
 * Backlinks to the project, grouped by source note type, ready for the
 * frontend to render and route on. Mirrors the domain `ProjectBacklinks`
 * grouping (which holds `VaultPath`s and carries no ts-rs derives).
 *
 * Each group is ordered newest-first by the domain — a project accrues
 * backlinks for as long as it runs, and the recent ones are the context a
 * reader wants — so the frontend renders the order it receives.
 */
export type BacklinksView = { portfolios: Array<BacklinkRow>, questions: Array<BacklinkRow>, evidence: Array<BacklinkRow>, actions: Array<BacklinkRow>, other: Array<BacklinkRow>, };
