// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialisable command error, tagged for the frontend to match on.
 *
 * The mapping from `DomainError` is deliberately lossy — the UI
 * needs a handful of *reactions* (show the cap modal, render a
 * disambiguation picker, toast a fixable message, toast a generic
 * failure), not the domain's full taxonomy. What must never be
 * lossy is the direction: a user-fixable error must not degrade to
 * `Internal` (which hides the message behind a generic toast) —
 * hence the exhaustive match below.
 */
export type CmdError = { "kind": "project_cap_reached", "data": { current: number, max: number, active: Array<string>, } } | { "kind": "not_found", "data": string } | { "kind": "ambiguous", "data": { query: string, candidates: Array<string>, } } | { "kind": "invalid", "data": string } | { "kind": "internal", "data": string };
