// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin of an aggregated commitment. The string payloads carry the
 * owning project / stewardship slug for context.
 */
export type CommitmentSource = { "kind": "project_milestone", "slug": string } | { "kind": "stewardship", "slug": string } | { "kind": "standalone_commitment", "slug": string } | { "kind": "action_note", "slug": string };
