// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentSource } from "./CommitmentSource";

/**
 * One dated commitment in the aggregated view produced by
 * [`Vault::commitments`]. The `source` records where it came from so
 * callers (orient, the commitments CLI) can group or label entries.
 */
export type CommitmentEntry = { date: string, title: string, source: CommitmentSource, 
/**
 * `true` when `date` is strictly before the query's `today`.
 */
is_overdue: boolean, };
