// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentEntry } from "./CommitmentEntry";

/**
 * The Commitments Timeline's data bundle: the aggregated entries plus
 * the date they were computed for. `today` lets the frontend split
 * "slipped past" from "upcoming" and label months without touching a
 * clock — the same discipline as `OrientationView.today`.
 */
export type CommitmentsView = { 
/**
 * The date the aggregation was computed for (stamped in Rust).
 */
today: string, entries: Array<CommitmentEntry>, };
