// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentSource } from "./CommitmentSource";
import type { Context } from "./Context";

/**
 * One dated commitment in the aggregated view produced by
 * [`Vault::commitments`]. The `source` records where it came from so
 * callers (orient, the commitments CLI) can group or label entries.
 */
export type CommitmentEntry = { date: string, title: string, source: CommitmentSource, 
/**
 * `true` when `date` is strictly before the query's `today`.
 */
is_overdue: boolean, 
/**
 * Life-domain of the owning note, so the Home commitments strip
 * can colour-code each row by context (#54). Resolved from the
 * source note's frontmatter: the project map for milestones and
 * action notes, the stewardship dashboard for periodic
 * commitments, the note itself for standalone commitments.
 */
context: Context, };
