// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One completed action in the reviewed week, flattened from the domain
 * `CompletedActionEntry` (which carries a `VaultPath` that can't hold a
 * `ts-rs` derive). The seed line needs only title + project.
 */
export type CompletedActionView = { slug: string, project: string, title: string, completed: string, };
