// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for [`CONFIG_STATUS`]. `valid:false` carries the open error's
 * `message` (the app kept the last good config); `valid:true` clears any
 * prior notice and carries no message. Exported to TS because the UI
 * surfaces the notice as a non-red banner (GH #365 PR4).
 */
export type ConfigStatus = { valid: boolean, message: string | null, };
