// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A human-readable reason a candidate config would fail to open —
 * either a TOML syntax error (with the line/column TOML reports) or a
 * domain validation error (a reserved-name shadow, a bad folder, a
 * redeclared period key, …).
 *
 * This is the SAME error [`validate_config_str`] returns for both the
 * PR1 dry-run and the eventual PR3 save gate, so the two cannot
 * disagree. `line`/`col` are populated only for a TOML parse failure;
 * validation errors carry a message alone.
 */
export type ConfigValidationError = { 
/**
 * The full, human-readable message. For a TOML parse error this is
 * TOML's own rendering (which already names the line/column and
 * shows the offending snippet); for a validation error it is the
 * domain error's `Display`.
 */
message: string, 
/**
 * 1-based line of a TOML parse error, when TOML reports a span.
 */
line: number | null, 
/**
 * 1-based column of a TOML parse error, when TOML reports a span.
 */
col: number | null, };
