// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The raw `.cuaderno/config.toml` text plus a content hash, returned by
 * [`Vault::read_config_raw`]. Serialised verbatim to the desktop Config
 * inspector.
 *
 * `hash` is `cdno_core::hash::content_hash` of `content` — the same
 * fingerprint reconciliation uses. It is load-bearing for a future
 * compare-and-swap write (PR3): the read hands the UI a hash it can
 * echo back on save so a concurrent hand-edit is detected rather than
 * clobbered.
 */
export type ConfigDocument = { 
/**
 * The verbatim file text — comments, ordering, and `[variables]`
 * all preserved. Empty when the file is absent (a vault always has
 * a config, but the read is defensive).
 */
content: string, 
/**
 * A 16-char lowercase-hex content hash of `content`.
 */
hash: string, };
