// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigValidationError } from "./ConfigValidationError";

/**
 * Why a [`Vault::save_config_raw`] call was rejected — the three
 * distinct failure modes a config save can hit, tagged so the desktop
 * UI can react to each precisely (show the validation message inline,
 * prompt a reload on a concurrent edit, or toast a generic failure).
 *
 * The ordering of the variants mirrors the save gate's own order:
 * [`Validation`](Self::Validation) is checked FIRST and is the
 * never-brick guarantee — a candidate that would not reopen is rejected
 * before anything is written; [`Conflict`](Self::Conflict) is the
 * compare-and-swap guard against a concurrent hand-edit; and
 * [`Internal`](Self::Internal) covers a store/disk fault.
 */
export type ConfigSaveError = { "kind": "validation", "data": ConfigValidationError } | { "kind": "conflict" } | { "kind": "internal", "data": string };
