// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The health of the on-disk config after an external-edit reload
 * (GH #365 PR4, #384). Three outcomes the UI renders distinctly.
 */
export type ConfigHealth = "valid" | "invalid" | "deferred";
