// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedNoteType } from "./NamedNoteType";
import type { NamedSchema } from "./NamedSchema";
import type { VaultMeta } from "./VaultMeta";

/**
 * A serialisable projection of the parsed config for the structured
 * Config view (#365, PR5a) — the vault meta, the `[note_types.*]`
 * table, and the `[schemas.*]` table, each named and sorted. Distinct
 * from [`ConfigDocument`], which carries the raw file text for the raw
 * editor: this is the typed, form-facing shape the read-only structured
 * panel renders.
 *
 * A dedicated view-model rather than serialising `VaultConfig` directly:
 * `VaultConfig` isn't `Serialize`/`TS` (its `[variables]` block uses
 * `#[serde(flatten)]`, which ts-rs can't follow), and PR5a renders only
 * the meta/note-types/schemas slice — variables and `ignore` stay out of
 * the form for now.
 */
export type ConfigModel = { 
/**
 * The `[vault]` section — name and the active-project cap.
 */
vault: VaultMeta, 
/**
 * Every `[note_types.<name>]`, sorted by `name` — a `HashMap`
 * iterates in an unspecified order, so the projection sorts for a
 * stable render (and stable tests).
 */
note_types: Array<NamedNoteType>, 
/**
 * Every `[schemas.<name>]`, sorted by `name` — same stable-order
 * rationale as `note_types`.
 */
schemas: Array<NamedSchema>, };
