// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedNoteType } from "./NamedNoteType";
import type { NamedSchema } from "./NamedSchema";
import type { VariablesModel } from "./VariablesModel";
import type { VaultMeta } from "./VaultMeta";

/**
 * A serialisable projection of the parsed config for the structured
 * Config view (#365, PR5a) — the vault meta, the `[note_types.*]` table,
 * the `[schemas.*]` table, and the `[variables]` block (#376), each named
 * and sorted. Distinct from [`ConfigDocument`], which carries the raw file
 * text for the raw editor: this is the typed, form-facing shape the
 * structured panel renders.
 *
 * A dedicated view-model rather than serialising `VaultConfig` directly:
 * `VaultConfig` isn't `Serialize`/`TS` (its `[variables]` block uses
 * `#[serde(flatten)]`, which ts-rs can't follow), so the projection lifts
 * the flattened variables into named lists ([`VariablesModel`]). Only the
 * top-level `ignore` globs stay out of the form for now.
 */
export type ConfigModel = { 
/**
 * The `[vault]` section — name and the active-project cap.
 */
vault: VaultMeta, 
/**
 * Every `[note_types.<name>]`, sorted by `name` — a `HashMap`
 * iterates in an unspecified order, so the projection sorts for a
 * stable render (and stable tests).
 */
note_types: Array<NamedNoteType>, 
/**
 * Every `[schemas.<name>]`, sorted by `name` — same stable-order
 * rationale as `note_types`.
 */
schemas: Array<NamedSchema>, 
/**
 * The `[variables]` block — static and prompted template variables,
 * each lifted into a sorted, named list (#376).
 */
variables: VariablesModel, };
