// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigHealth } from "./ConfigHealth";

/**
 * Payload for [`CONFIG_STATUS`]. `message` carries the open/transient error
 * detail for `Invalid` / `Deferred`; `Valid` clears any prior notice and
 * carries no message. Exported to TS because the UI surfaces the notice as
 * a non-red banner (GH #365 PR4, #384).
 */
export type ConfigStatus = { health: ConfigHealth, message: string | null, };
