// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A daily note plus the neighbour identities the calendar panel's
 * quick-nav needs, so the frontend never computes a domain date for a
 * read (plan §3.7). Absence is a normal answer (`exists: false`, empty
 * `markdown`) the panel renders as a calm empty state, not an error.
 */
export type DailyView = { 
/**
 * The note's own date (`YYYY-MM-DD`), echoed back so the panel can
 * label itself without re-parsing the request.
 */
date: string, 
/**
 * Whether a note file exists for the day — the panel branches on
 * this to show the note or the empty state.
 */
exists: boolean, 
/**
 * The daily note's markdown (empty when `exists` is false).
 */
markdown: string, 
/**
 * The note's vault-relative path — always resolved, even when the
 * note doesn't exist yet, so "Open in editor" works from the empty
 * state too.
 */
path: string, 
/**
 * The day before `date` — the prev-day quick-nav target.
 */
prev_date: string, 
/**
 * The day after `date` — the next-day quick-nav target.
 */
next_date: string, 
/**
 * The Monday of `date`'s ISO week — the week quick-nav target,
 * echoed straight into `read_weekly`.
 */
week_of: string, 
/**
 * `date`'s calendar month as `YYYY-MM` — the month quick-nav target,
 * echoed straight into `read_monthly`.
 */
month: string, };
