// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Effort/focus tag attached to a next action, displayed as a
 * parenthesised suffix (`- [ ] Run ablation (deep)`). Drives the
 * energy selector in the daily orientation view (§5.2 of the design
 * doc) — the user picks an energy level and the UI surfaces actions
 * matching that level.
 */
export type EnergyLevel = "deep" | "medium" | "light";
