// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One evidence note in the detail's timeline — the domain
 * `EvidenceFrontmatter` with its `VaultPath` lowered to a wire string
 * so the frontend can open the note in the reader and render its date,
 * source, and origin chip.
 */
export type EvidenceRow = { path: string, created: string, source: string, 
/**
 * Bare wikilink target of the evidence `origin` (brackets
 * stripped), e.g. `"projects/surrogate-model"`. The frontend
 * resolves it to open the producing note in the reader.
 */
origin: string, };
