// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldType } from "./FieldType";

/**
 * A typed frontmatter field declared under `[schemas.<type>.fields.<name>]`
 * (`#301`).
 *
 * `deny_unknown_fields` turns a mistyped key (`defualt = …`) into a hard
 * parse error rather than a silently-ignored no-op — a schema typo is a
 * footgun worth failing on.
 */
export type FieldSpec = { 
/**
 * The field's scalar type (TOML key `type`).
 */
type: FieldType, 
/**
 * A static default value, type-checked against `ty` at load. TOML has no
 * null, so an absent `default` means "no default" (`None`). Populating a
 * note with this value is PR-B; PR-A only validates it.
 */
default: string | number | boolean | null, 
/**
 * Whether the field must be present. Only an *explicit* `required = true`
 * will opt a field into create-time erroring; the desugared
 * `extra_required` view keeps this `false` (lint-only).
 *
 * INERT through PR-B — nothing reads this yet. PR-B populates declared
 * *defaults* at create but deliberately leaves `required` toothless,
 * because Phase 1 has no create surface that supplies a caller value for a
 * built-in's schema field: erroring on absence would break every create.
 * Create-time required-enforcement lands in **Phase 2** (the
 * `set_frontmatter` setter / `--var` supply path), together with its
 * load-time guard "`required` without a `default` is a load error on
 * lazily-scaffolded types (daily/weekly/monthly/inbox)" — otherwise the
 * first `append_to_log` of a day would scaffold a daily note missing a
 * required-no-default field and fail (the checkpoint-logging cliff). Both
 * arrive in the same phase so the cliff cannot open in PR-B by
 * construction.
 */
required: boolean, 
/**
 * An allowed-value constraint on a `string` field — the "enum" shape
 * without a dedicated type. Rejected on a non-string field by
 * [`VaultConfig::validate_schemas`].
 */
values: Array<string> | null, 
/**
 * RESERVED (`#301`): a list/array field. Parsed so the grammar is fixed
 * now, but `list = true` is a load error ("not yet implemented") in P1 so
 * the shape can be added source-compatibly later.
 */
list: boolean | null, 
/**
 * RESERVED for the Phase-2 setter: whether the field may be changed by
 * `set_frontmatter`. Parsed but unused in P1.
 */
settable: boolean | null, 
/**
 * RESERVED for the Phase-2 setter: whether a change should be auto-logged
 * to the daily note. Parsed but unused in P1.
 */
log_on_change: boolean | null, };
