// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scalar type a `[schemas.<type>.fields.<name>]` declares. Deliberately
 * small (`#301`): a link-heavy list shape is reserved via [`FieldSpec::list`]
 * rather than by adding array variants here, and an "enum" is expressed as a
 * `string` constrained by [`FieldSpec::values`] rather than a distinct type.
 *
 * An unknown `type = "…"` is a hard deserialize error (serde rejects any value
 * outside these variants) — so a future `float`/`datetime` fails loudly on an
 * older `cdno` rather than being silently misparsed.
 */
export type FieldType = "bool" | "int" | "string" | "date";
