// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One uncategorised capture under `inbox/` awaiting triage.
 */
export type InboxItem = { 
/**
 * Filename stem (`<YYYY-MM-DD>-<slug>`) — the handle passed to
 * [`Vault::discard_inbox_item`].
 */
slug: string, 
/**
 * The captured text (the note body, trimmed).
 */
text: string, };
