// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many markdown files the startup reconciliation left out of the
 * index, and why (#440).
 *
 * A file absent from the index is absent from search, lint and backlinks
 * too, so the counts have to be reachable — the app previously logged
 * only added/updated/removed and dropped these on the floor, which is how
 * an over-broad `ignore` glob could evict every portfolio note and present
 * as "the Portfolios section is broken" rather than "my config is wrong".
 *
 * Delivered as a queryable command rather than a startup event: the
 * webview may not be listening when reconciliation finishes, and a notice
 * the user never sees is the failure being fixed.
 */
export type IndexExclusions = { 
/**
 * Markdown excluded by the config `ignore` globs.
 */
ignored: number, 
/**
 * Markdown skipped as attachment artefacts owned by an evidence stub.
 * Excluded by design, never a sign of misconfiguration.
 */
artefacts: number, 
/**
 * Markdown files that did make it into the index.
 */
indexed: number, 
/**
 * Whether `ignored` is large enough to suggest an over-broad glob
 * rather than deliberate housekeeping. See [`glob_looks_over_broad`].
 */
ignore_looks_over_broad: boolean, };
