// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many markdown files the most recent reconciliation left out of
 * the index, and why (#440). Every pass rewrites it — the startup one,
 * a config rebuild, and each of the watcher's.
 *
 * A file absent from the index is absent from search, lint and backlinks
 * too, so the counts have to be reachable — the app previously logged
 * only added/updated/removed and dropped these on the floor, which is how
 * an over-broad `ignore` glob could evict every portfolio note and present
 * as "the Portfolios section is broken" rather than "my config is wrong".
 *
 * Delivered as a queryable command rather than a startup event: the
 * webview may not be listening when reconciliation finishes, and a notice
 * the user never sees is the failure being fixed.
 */
export type IndexExclusions = { 
/**
 * Markdown excluded by the config `ignore` globs.
 */
ignored: number, 
/**
 * Markdown skipped as attachment artefacts owned by an evidence stub.
 * Excluded by design, never a sign of misconfiguration.
 */
artefacts: number, 
/**
 * Markdown files that did make it into the index.
 */
indexed: number, 
/**
 * Whether `ignored` is large enough to suggest an over-broad glob
 * rather than deliberate housekeeping. See [`glob_looks_over_broad`].
 */
ignore_looks_over_broad: boolean, 
/**
 * Bumped once per config rebuild, and only there.
 *
 * The notice is dismissible, and a dismissal has to survive ordinary
 * vault growth: in the very vault this exists for, a glob swallowing a
 * tree means every note filed into that tree changes the counts. But it
 * must NOT survive the user editing their globs — swapping one
 * over-broad pattern for another never shows an intermediate healthy
 * state, so a dismissal keyed on the condition alone would silence the
 * notice for the rest of the session. This counter is what the frontend
 * keys on: it moves when the globs might have, and not otherwise.
 */
config_generation: number, };
