// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stewardship habit whose `## Active Habits` line declares a lapse
 * (design §5.6 — e.g. "Swimming 1x/week — lapsed since March").
 */
export type LapsedHabit = { 
/**
 * Slug of the owning stewardship.
 */
stewardship: string, 
/**
 * Human-readable description of the lapse.
 */
detail: string, };
