// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One daily-log line mentioning the project, for the "recently in
 * your logs" strip. Flattened from the domain `DailyLogLine`.
 */
export type LogMentionView = { date: string, 
/**
 * The log line's timestamp (`HH:MM:SS`).
 */
time: string, text: string, };
