// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open milestone, flattened from the core `MilestoneEntry` (which
 * lives in `cdno-core` and can't carry ts-rs derives) into a
 * wire-ready shape.
 */
export type MilestoneView = { name: string, 
/**
 * ISO `YYYY-MM-DD`, or `None` for a non-date marker (`target: Q3`).
 */
date: string | null, 
/**
 * `true` for a `hard:` deadline, `false` for a soft target.
 */
is_hard: boolean, };
