// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A monthly note's raw content for the calendar panel's month jump
 * (#228). Absence-tolerant like `DailyView`.
 */
export type MonthlyView = { 
/**
 * The month the note covers, as `YYYY-MM`, echoed back.
 */
month: string, exists: boolean, markdown: string, 
/**
 * The note's vault-relative path (resolved even when absent, for
 * "Open in editor").
 */
path: string, };
