// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaExtension } from "./SchemaExtension";

/**
 * One `[schemas.<name>]` entry: the map key lifted alongside its
 * extension. Same no-flatten shape as [`NamedNoteType`].
 */
export type NamedSchema = { name: string, schema: SchemaExtension, };
