// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `[variables]` (static) or `[variables.prompt]` (prompted) entry: the
 * map key lifted alongside its value. Same no-flatten shape as
 * [`NamedNoteType`] — the `[variables]` block uses `#[serde(flatten)]`, which
 * ts-rs can't follow, so the form projects it into named lists instead (#376).
 */
export type NamedValue = { name: string, value: string, };
