// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomNoteType } from "./CustomNoteType";

/**
 * One `[note_types.<name>]` entry: the map key lifted alongside its
 * definition. Not `#[serde(flatten)]`-ed (ts-rs friction) — the name
 * rides as its own field.
 */
export type NamedNoteType = { name: string, note_type: CustomNoteType, };
