// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One vault note, split for display: typed metadata from the index,
 * frontmatter as JSON, and the markdown body ready for rendering.
 */
export type NoteView = { 
/**
 * Serialised as a plain string over the wire (VaultPath's Display
 * form).
 */
path: string, 
/**
 * The index row's note type (e.g. `"project"`, `"tracking"`), or
 * `None` when the file isn't indexed — attachments, ignored
 * files, or a note written since the last reconcile.
 */
note_type: string | null, 
/**
 * Text of the body's first ATX H1, when present.
 */
title: string | null, 
/**
 * Full frontmatter as JSON. `null` when the file has no parseable
 * frontmatter block. Typed as `unknown` on the wire — the renderer
 * narrows per note type.
 */
frontmatter: unknown, 
/**
 * Markdown body after the closing `---` (or the whole file when
 * there is no frontmatter block).
 */
body: string, };
