// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Context } from "./Context";

/**
 * What the user is in the middle of, for the Today page's Now band
 * (#442).
 *
 * Reconstructed from today's daily log — starting an action writes a
 * line, completing it writes another — so it needs no state of its own
 * and picks up a start made from the CLI or by an agent over MCP, not
 * only one clicked in the app.
 */
export type NowView = { 
/**
 * The project slug the action belongs to; routes to its map.
 */
project: string, 
/**
 * Life context of that project, for the colour dot. Absent if the
 * project has since been renamed or removed — the band still shows
 * what the log says rather than dropping the entry.
 */
context: Context | null, 
/**
 * The action text as logged.
 */
action: string, 
/**
 * `HH:MM` the action was started, for the "since" label. The elapsed
 * time is computed in the frontend so it can tick without a refetch.
 */
started: string, };
