// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionListEntry } from "./ActionListEntry";
import type { Context } from "./Context";
import type { ProjectStatus } from "./ProjectStatus";
import type { TopAction } from "./TopAction";

export type OrientationProject = { 
/**
 * All open bullets from `## Next Actions`, for the energy
 * filter's no-match rule (a card never blanks).
 */
actions: Array<ActionListEntry>, slug: string, status: ProjectStatus, 
/**
 * Life context from the frontmatter — drives the UI's colour
 * dot. Carried here so orientation consumers get it in the same
 * pass that reads the map (a separate lookup could race a
 * concurrent park/rename into a silently wrong colour).
 */
context: Context, state_snippet: string, top_action: TopAction | null, };
