// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionListEntry } from "./ActionListEntry";
import type { Context } from "./Context";
import type { ProjectStatus } from "./ProjectStatus";
import type { TopAction } from "./TopAction";

export type OrientationProject = { context: Context, 
/**
 * All open bullets from `## Next Actions`, for the energy
 * filter's no-match rule (a card never blanks).
 */
actions: Array<ActionListEntry>, slug: string, status: ProjectStatus, state_snippet: string, top_action: TopAction | null, };
