// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentEntry } from "./CommitmentEntry";
import type { LapsedHabit } from "./LapsedHabit";
import type { OrientationProject } from "./OrientationProject";

/**
 * The Home view's bundle (plan §1.1): `orientation_context` plus,
 * per project, the life context (for the colour dot) and *every*
 * open action bullet — the energy selector filters client-side, so
 * one invoke carries the whole morning.
 */
export type OrientationView = { 
/**
 * The date the snapshot was computed for (stamped in Rust — the
 * frontend never computes domain dates).
 */
today: string, commitments: Array<CommitmentEntry>, projects: Array<OrientationProject>, lapsed_habits: Array<LapsedHabit>, };
