// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a template placeholder's value comes from — the classification
 * [`Vault::template_placeholders`] attaches to each name.
 *
 * Serialised adjacently-tagged (`{ "kind": "supplied" }`,
 * `{ "kind": "prompt", "data": { "message": … } }`) for the desktop
 * Templates view's placeholder-reference panel, which groups the set by
 * `kind`.
 */
export type PlaceholderSource = { "kind": "supplied" } | { "kind": "schema" } | { "kind": "config" } | { "kind": "prompt", "data": { message: string, } };
