// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a metric is drawn, when it is drawn at all (`#483`).
 *
 * Chooses the **mark** a series is drawn with (`#486`). It does not yet gate
 * **whether** it is drawn (`#500`): the derivation emits a series for every
 * declared metric regardless, and the desktop draws every series it is given.
 * So declaring an activity does change what is drawn today — its frontmatter
 * series replace its body-table ones.
 *
 * Presentation vocabulary, carried here for the same reason [`FieldType`] is
 * — it is deserialised from config — but it is the one type in this crate
 * that the crate neither parses for itself nor interprets; it flows through
 * to the DTO. A deliberate exception to core's no-domain-knowledge contract.
 */
export type PlotKind = "none" | "line" | "column" | "area" | "scatter";
