// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a metric is drawn, when it is drawn at all (`#483`).
 *
 * Chooses the **mark** a series is drawn with (`#486`) and, since `#500`,
 * gates **whether** the desktop draws it: the derivation still emits a
 * series for every declared metric regardless of `plot` — so `#485`'s
 * body-table suppression keeps keying on the full produced set — but the
 * desktop filters `None` out of the chart pane at the presentation
 * boundary. The series stays collected and queryable over MCP either way.
 *
 * Presentation vocabulary, carried here for the same reason [`FieldType`] is
 * — it is deserialised from config — but it is the one type in this crate
 * that the crate neither parses for itself nor interprets; it flows through
 * to the DTO. A deliberate exception to core's no-domain-knowledge contract.
 */
export type PlotKind = "none" | "line" | "column" | "area" | "scatter";
