// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a metric is drawn, when it is drawn at all (`#483`).
 *
 * Presentation vocabulary, carried here for the same reason [`FieldType`] is
 * — it is deserialised from config — but it is the one type in this crate
 * that the crate neither parses for itself nor interprets; it flows through
 * to the DTO. A deliberate exception to core's no-domain-knowledge contract.
 */
export type PlotKind = "none" | "line" | "column" | "area" | "scatter";
