// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the `Vault::list_portfolios` output. Aggregates per-
 * portfolio metadata that's expensive to recompute by hand: the
 * number of evidence notes filed into the folder, the most recent
 * `created` date among them, and a derived staleness in days.
 */
export type PortfolioSummary = { slug: string, question: string, evidence_count: number, 
/**
 * `created` date of the most recent evidence note in the folder,
 * or `None` for a portfolio that has no evidence yet.
 */
last_updated: string | null, 
/**
 * Days from `today` (passed into `list_portfolios`) back to
 * `last_updated`. `None` when there's no evidence to measure
 * against. Negative for evidence dated in the future (rare;
 * mostly catches typos).
 */
staleness_days: bigint | null, };
