// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceRow } from "./EvidenceRow";

/**
 * The composed Portfolio Detail view-model (plan §1.6). One invoke
 * backs the whole `/portfolios/:slug` page: the portfolio's unifying
 * question, its links (the `project:` frontmatter and the related
 * questions the body wikilinks), and every filed evidence note as a
 * wire-ready row, newest first.
 */
export type PortfolioDetail = { slug: string, 
/**
 * The unifying question the portfolio collects evidence against
 * (the `question` frontmatter field, shown as the page title).
 */
question: string, created: string, 
/**
 * Bare wikilink target of the linked project (brackets stripped,
 * e.g. `"projects/surrogate-model"`), or `None` for a standalone
 * portfolio. The frontend navigates to `/projects/:slug`.
 */
project: string | null, 
/**
 * Bare wikilink targets of the related question notes the
 * portfolio body links (from its `## Related Questions`), e.g.
 * `"questions/research/foo"`. Opened in the reader on click.
 */
questions: Array<string>, 
/**
 * Every evidence note filed under the portfolio, newest first.
 */
evidence: Array<EvidenceRow>, };
