// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionListEntry } from "./ActionListEntry";
import type { BacklinksView } from "./BacklinksView";
import type { Context } from "./Context";
import type { LogMentionView } from "./LogMentionView";
import type { MilestoneView } from "./MilestoneView";
import type { ProjectStatus } from "./ProjectStatus";

/**
 * The Project Detail view-model (plan §1.8). Composes the project map
 * (typed frontmatter fields + raw body) with its actions, open
 * milestones, backlinks, and recent log mentions — everything the
 * `/projects/:slug` page renders, in one invoke.
 */
export type ProjectDetail = { slug: string, 
/**
 * The project's lifecycle status — `parked` renders the page
 * read-only (no action ticks / adds), so the frontend needs it
 * even though a parked project still shows its map and history.
 */
status: ProjectStatus, context: Context, created: string, 
/**
 * The raw `core_question` wikilink string, when the project sets
 * one (`"[[questions/research/foo]]"`). Resolution is the
 * frontend's job via `resolve_wikilink`.
 */
core_question: string | null, 
/**
 * The project map's markdown body (below the frontmatter), for
 * the Links section and any prose the structured fields don't
 * capture.
 */
body_markdown: string, 
/**
 * Open action bullets. Empty for a parked project — `list_actions`
 * refuses parked projects, and the detail page renders them
 * read-only anyway (see `get_project_impl`).
 */
actions: Array<ActionListEntry>, open_milestones: Array<MilestoneView>, backlinks: BacklinksView, log_mentions: Array<LogMentionView>, };
