// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Context } from "./Context";
import type { ProjectStatus } from "./ProjectStatus";
import type { TopAction } from "./TopAction";

/**
 * Compact view of a project for orientation displays and reviews.
 *
 * `state_snippet` is the first two non-blank lines of `## Current
 * State`, joined with `\n`. Empty when the section is missing or
 * has no content. `top_action` is the first open `- [ ]` bullet in
 * `## Next Actions` (closed bullets and blanks skipped); `None`
 * when nothing is open.
 */
export type ProjectSummary = { slug: string, status: ProjectStatus, 
/**
 * Life context from the frontmatter — drives the UI's colour
 * dot. Carried here so orientation consumers get it in the same
 * pass that reads the map (a separate lookup could race a
 * concurrent park/rename into a silently wrong colour).
 */
context: Context, state_snippet: string, top_action: TopAction | null, };
