// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Context } from "./Context";

/**
 * One project in the allocator or on the parked shelf — a deliberately
 * thin view over the project frontmatter. The slug identifies the note
 * (and routes to `/projects/:slug`); the context drives the colour
 * dot. The project's display name is its map H1, not a frontmatter
 * field, so it isn't carried here — the slug reads well enough for the
 * allocator's compact chips, and skipping the H1 keeps the bundle to
 * one read per project rather than two.
 */
export type ProjectSlot = { slug: string, context: Context, };
