// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a project. Park/activate transitions cap-check
 * against `max_active_projects`; completion is terminal.
 */
export type ProjectStatus = "active" | "parked" | "completed";
