// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionListEntry } from "./ActionListEntry";
import type { Context } from "./Context";

/**
 * One active project's open actions, for the cross-project Actions
 * view (plan §1.2). Carries the slug and life `context` (for the
 * colour dot) alongside the bullets so the view groups and tints
 * without a second read.
 */
export type ProjectActions = { slug: string, context: Context, actions: Array<ActionListEntry>, };
