// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionDomain } from "./QuestionDomain";
import type { QuestionStatus } from "./QuestionStatus";

/**
 * One row in the `Vault::active_questions` / `Vault::list_questions`
 * output. Carries enough for a renderer to display the question
 * without re-reading the file: the slug (filename stem, used for
 * lookups), the domain (for grouping), the status (for badging and
 * filtering by the CLI pickers), the question text (extracted from
 * the body H1), and the most recent update date.
 */
export type QuestionSummary = { slug: string, domain: QuestionDomain, status: QuestionStatus, 
/**
 * The question text from the body H1. Empty string if the file
 * has no H1 — lint will flag that separately.
 */
question_text: string, updated: string, };
