// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionBacklinksView } from "./QuestionBacklinksView";
import type { QuestionSummary } from "./QuestionSummary";

/**
 * One question row in the strategic grid: the summary paired with its
 * backlinks bucketed by source note type (#354). Mirrors
 * [`StewardshipStrategicRow`] — a domain summary plus a precomputed
 * companion the grid renders without a second query.
 */
export type QuestionStrategicRow = { summary: QuestionSummary, backlinks: QuestionBacklinksView, };
