// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a question. The four variants are the design
 * vocabulary (§5.8): `active` lives on the orientation surface,
 * `parked` is interesting-but-not-now, `answered` is resolved-and-
 * kept-for-reference, `retired` is no-longer-relevant. The file
 * stays in place across every transition — only the frontmatter
 * changes — so backlinks from projects and portfolios survive.
 */
export type QuestionStatus = "active" | "parked" | "answered" | "retired";
