// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A question's backlinks, grouped by source note type, as path strings
 * ready for the frontend to render and route on (#354). The frontend-side
 * mirror of the domain `QuestionBacklinks` (which holds `VaultPath`s and
 * carries no ts-rs derives) — the same shape `BacklinksView` gives the
 * project detail page.
 */
export type QuestionBacklinksView = { projects: Array<string>, portfolios: Array<string>, evidence: Array<string>, other: Array<string>, };
