// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of question this is. Drives the on-disk folder
 * (`questions/research/` vs `questions/life/`). Closed enum: design
 * §5.8 names exactly these two; adding a third should be a conscious
 * decision rather than a typo silently creating a new folder.
 */
export type QuestionDomain = "research" | "life";
