// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resolved destination of a single wikilink target, for typed UI
 * navigation. `path` is the vault-relative note the target points at;
 * `note_type` is the index row's type (`"project"`, `"stewardship"`,
 * …) so the frontend can route to a typed view rather than always
 * falling back to the generic note reader. `note_type` is `None` when
 * the resolved file has no index row (written since the last
 * reconcile, or an ignored file).
 */
export type ResolvedLink = { 
/**
 * Serialised as a plain string over the wire (VaultPath's Display
 * form) — the same shape every other path field promises.
 */
path: string, note_type: string | null, };
