// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked search hit, domain-side. Mirrors the core
 * [`SearchHit`](cdno_core::index::SearchHit); kept as its own type so the
 * domain surface owns its result shape (and can diverge later) rather
 * than leaking the core struct through every caller.
 */
export type SearchResultEntry = { 
/**
 * Serialised as a plain string over the wire (VaultPath's Display
 * form).
 */
path: string, note_type: string, title: string | null, snippet: string, 
/**
 * Raw bm25 relevance — lower is a better match (the sort key).
 */
score: number, };
