// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a Current State update that exceeds [`VaultMeta::max_state_chars`]
 * is handled. Serialised as a lowercase string in `config.toml`
 * (`state_overflow = "reject"`).
 */
export type StateOverflow = "reject" | "warn" | "off";
