// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Context } from "./Context";
import type { StewardshipVariant } from "./StewardshipVariant";

/**
 * One row in the `Vault::list_stewardships` output. Aggregates
 * per-stewardship metadata that's expensive to recompute by hand:
 * the variant, the count of tracking notes filed into the folder,
 * and the most recent tracking date (the staleness proxy that
 * stands in for a hard "status" field — design §5.6 keeps the
 * dashboard's status as prose in the body).
 */
export type StewardshipSummary = { slug: string, 
/**
 * The dashboard's body H1. Empty string if absent — lint will
 * flag that separately.
 */
name: string, context: Context, variant: StewardshipVariant, 
/**
 * Always `0` for [`StewardshipVariant::Flat`]: flat dashboards
 * have no `tracking/` subdir by design.
 */
tracking_count: number, 
/**
 * `date` of the most recent tracking note in the folder, or
 * `None` when none exists yet.
 */
last_tracking_date: string | null, 
/**
 * Days from `today` (passed into [`list_stewardships`]) back to
 * `last_tracking_date`. `None` when there's no tracking to
 * measure against. Negative for future-dated tracking (rare;
 * catches typos).
 */
staleness_days: bigint | null, };
