// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StewardshipSummary } from "./StewardshipSummary";

/**
 * One row of the stewardship overview: the summary the list surface
 * already computes, paired with a precomputed habit sparkline.
 *
 * The sparkline is a `Vec<u32>` of tracking-entry counts, one per ISO
 * week over the last [`SPARKLINE_WEEKS`], oldest week first and the
 * current week last. Empty for a flat stewardship (no `tracking/`
 * subdir to count) — the frontend draws the spark only when it's
 * non-empty, mirroring the detail view's "charts pane only when
 * there's data" rule.
 */
export type StewardshipStrategicRow = { summary: StewardshipSummary, sparkline: Array<number>, };
