// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which on-disk variant a stewardship lives as. Drives where tracking
 * notes can land (only expanded stewardships have a `tracking/`
 * subdirectory) and what `cdno stewardship show` (#44) renders.
 */
export type StewardshipVariant = "flat" | "expanded";
