// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Context } from "./Context";
import type { StewardshipVariant } from "./StewardshipVariant";
import type { TrackingEntryView } from "./TrackingEntryView";
import type { TrackingSeries } from "./TrackingSeries";

/**
 * The composed Stewardship Detail view-model (plan §1.7). One invoke
 * backs the whole `/stewardships/:slug` page: the dashboard body, the
 * trend series (empty for a flat stewardship — no `tracking/` subdir,
 * so the frontend omits the charts pane), and the last-few tracking
 * entries with a body excerpt for inline preview.
 */
export type StewardshipDetail = { slug: string, 
/**
 * The dashboard's body H1 (empty when absent — lint flags that
 * separately). The frontend falls back to the slug for display.
 */
name: string, context: Context, variant: StewardshipVariant, 
/**
 * The dashboard markdown below the frontmatter, rendered verbatim
 * (status, habits, periodic commitments — the qualitative surface
 * that the charts never replace).
 */
body_markdown: string, 
/**
 * Numeric trend series, one per `(activity, table column)` pair
 * that ever carries a number. Empty for a flat stewardship — the
 * frontend shows the charts pane only when this is non-empty.
 */
series: Array<TrackingSeries>, 
/**
 * The most-recent tracking entries (up to five, newest first),
 * flattened from the domain `TrackingEntry` (whose `VaultPath`
 * can't carry a ts-rs derive) into a wire-ready shape.
 */
recent: Array<TrackingEntryView>, 
/**
 * Total tracking notes filed under this stewardship — the honest
 * count behind the "N tracked" line, not just the previewed five.
 */
tracking_count: number, };
