// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentEntry } from "./CommitmentEntry";
import type { PortfolioSummary } from "./PortfolioSummary";
import type { ProjectSlot } from "./ProjectSlot";
import type { QuestionStrategicRow } from "./QuestionStrategicRow";
import type { StewardshipStrategicRow } from "./StewardshipStrategicRow";

/**
 * The composed Strategic / Monthly data (plan §1.5). One read, every
 * panel: the resolved "today" (stamped in Rust, for the timeline and
 * staleness lines), the active questions to grid by domain, the
 * portfolio-health rows, the active / parked project slots plus the
 * configured cap the allocator lays out against, the stewardship
 * overview with a precomputed habit sparkline each, and the six-week
 * commitments lookahead.
 */
export type StrategicBundle = { 
/**
 * The real current date, stamped in Rust (plan §3.7) — the shared
 * timeline labels months and splits past/upcoming against it, and
 * the portfolio-health tiers read their staleness from it.
 */
today: string, 
/**
 * Every `status: active` question, sorted `(domain, slug)`, each with
 * its backlinks bucketed by source note type. The frontend groups by
 * domain (research / life) for the grid and renders project / evidence
 * chips from the backlinks alongside the portfolio chips (#354).
 */
questions: Array<QuestionStrategicRow>, 
/**
 * Per-question evidence dossiers with their counts and staleness,
 * for the portfolio-health table. Reused verbatim from the M8
 * browser so the two surfaces can't disagree on the numbers.
 */
portfolios: Array<PortfolioSummary>, 
/**
 * The active project slots the allocator fills, in index order.
 * `active.len()` is at most `max_active`; the frontend renders the
 * remaining `max_active - active.len()` slots as soft dashed "open
 * slot" placeholders (breathing room, not vacancy).
 */
active: Array<ProjectSlot>, 
/**
 * The parked shelf beneath the slots — each activatable back into
 * an open slot (or, at the cap, via the "park one to make space"
 * modal).
 */
parked: Array<ProjectSlot>, 
/**
 * The configured active-project cap (`max_active_projects`,
 * default 5) — the number of slots the allocator draws, read
 * straight from the vault config rather than hardcoded, so a vault
 * that raised or lowered the cap lays out the right count.
 */
max_active: number, 
/**
 * The stewardship overview rows: each carries its summary (context
 * dot, name, staleness) and a precomputed 12-week habit sparkline.
 */
stewardships: Array<StewardshipStrategicRow>, 
/**
 * Dated commitments for the six-week timeline: the next 42 days
 * forward, plus anything overdue within the domain's look-back
 * (the `commitments` query folds both together). Fed to the shared
 * `CommitmentsTimeline` in read-only mode.
 */
commitments: Array<CommitmentEntry>, };
