// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stuck active project: its slug and how many days its map has sat
 * unmodified. The frontend cross-references the slug against
 * `projects` to hang the grey "state untouched for N days" hint on the
 * matching card.
 */
export type StuckProject = { slug: string, days_unchanged: bigint, };
