// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One prompted field the tracking log form must gather for a given
 * activity — the `[variables.prompt]` names the resolved tracking
 * template references, with each prompt's message as the field label.
 */
export type TemplateField = { name: string, 
/**
 * The prompt message from `config.toml`'s `[variables.prompt]` —
 * the human label the form shows above the input.
 */
prompt: string, };
