// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which rung a template's effective content came from — the
 * serialisable, wire-facing mirror of [`TemplateSource`] (which lives in
 * `cdno-core` and carries no serde/ts-rs derives). Reported by
 * [`Vault::read_template`] and [`Vault::list_templates`] so the desktop
 * Templates view can say "custom override" vs "built-in default".
 */
export type TemplateSourceKind = "custom_variant" | "custom_base" | "builtin_variant" | "builtin_default";
