// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceholderSource } from "./PlaceholderSource";

/**
 * A `{{placeholder}}` a note type's template supports, plus where its
 * value comes from. Returned by [`Vault::template_placeholders`].
 */
export type TemplatePlaceholder = { name: string, source: PlaceholderSource, };
