// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateSourceKind } from "./TemplateSourceKind";

/**
 * The effective (resolved) content of a template plus its source rung,
 * returned by [`Vault::read_template`]. `source` is `None` when the
 * content is a synthesised starter for a custom type with no template
 * file — nothing on disk backs it yet.
 */
export type TemplateContent = { content: string, source: TemplateSourceKind | null, };
