// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateSourceKind } from "./TemplateSourceKind";

/**
 * One row of [`Vault::list_templates`]: a note type and the status of its
 * template. Built-in types always have an effective template (their
 * built-in default, unless overridden); a config-defined custom type may
 * have none yet, which the view offers to scaffold via
 * [`Vault::create_template`].
 */
export type TemplateSummary = { 
/**
 * The type key — `project`, `daily`, or a config custom type's name.
 */
note_type: string, 
/**
 * A capitalised label for the list (`project` → `Project`).
 */
display_name: string, 
/**
 * Whether this is a config-defined custom type (vs a built-in). The
 * view offers `Create` only for a custom type with no template.
 */
is_custom_type: boolean, 
/**
 * The effective template's source rung, or `None` for a custom type
 * that has no template file yet (nothing on disk backs it).
 */
source: TemplateSourceKind | null, 
/**
 * Whether a custom override file exists under `.cuaderno/templates/`.
 */
has_custom_file: boolean, 
/**
 * The vault-relative path the custom override lives (or would live)
 * at — always resolved, so "Open in editor" works even before a file
 * exists.
 */
path: string, };
