// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnergyLevel } from "./EnergyLevel";

/**
 * One next-action line, with its energy bucket parsed when the
 * `(deep)` / `(medium)` / `(light)` suffix is present. `energy`
 * is `None` for hand-edited bullets without a suffix.
 */
export type TopAction = { text: string, energy: EnergyLevel | null, };
