// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tracking note in the detail's Recent list — the domain
 * `TrackingEntry` with its `VaultPath` lowered to a wire string so
 * the frontend can open the note in the reader and render its date,
 * activity, and excerpt.
 */
export type TrackingEntryView = { path: string, stewardship: string, activity: string, date: string, duration_min: number | null, 
/**
 * Raw wikilink string when the note pins a routine, else `None`.
 */
routine: string | null, 
/**
 * First non-blank body line, capped for preview.
 */
body_excerpt: string, };
