// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlotKind } from "./PlotKind";
import type { TrackingPoint } from "./TrackingPoint";

/**
 * One numeric time series lifted from a stewardship's tracking
 * notes, ready for a trend chart. See [`Vault::tracking_series`].
 */
export type TrackingSeries = { 
/**
 * `"{activity} · {column header}"` — e.g. `"gym · Weight (kg)"`.
 */
name: string, 
/**
 * One point per tracking note that had a numeric value in the
 * column, sorted by date.
 */
points: Array<TrackingPoint>, 
/**
 * The declared unit (`min`, `kg`, `EUR`), when the metric names one.
 * `None` for a body-table series, which has no declaration behind it.
 */
unit: string | null, 
/**
 * A declared display name. A consumer falls back to [`name`](Self::name).
 */
label: string | null, 
/**
 * The declared chart mark. `None` leaves the choice to the consumer's
 * own heuristic — which is all a body-table series ever had, since
 * nothing declares its semantics.
 */
mark: PlotKind | null, };
