// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackingPoint } from "./TrackingPoint";

/**
 * One numeric time series lifted from a stewardship's tracking
 * notes, ready for a trend chart. See [`Vault::tracking_series`].
 */
export type TrackingSeries = { 
/**
 * `"{activity} · {column header}"` — e.g. `"gym · Weight (kg)"`.
 */
name: string, 
/**
 * One point per tracking note that had a numeric value in the
 * column, sorted by date.
 */
points: Array<TrackingPoint>, };
