// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedValue } from "./NamedValue";

/**
 * The `[variables]` block projected for the form (#376): static template
 * variables (available in every template) and prompted variables (resolved
 * interactively when a template uses them), each a sorted, named list.
 */
export type VariablesModel = { 
/**
 * `[variables]` direct keys — `<name> = "<value>"`.
 */
static_vars: Array<NamedValue>, 
/**
 * `[variables.prompt]` keys — `<name> = "<prompt message>"`.
 */
prompt: Array<NamedValue>, };
