// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateOverflow } from "./StateOverflow";

/**
 * The `[vault]` section — basic vault metadata.
 */
export type VaultMeta = { name: string, max_active_projects: number, 
/**
 * Maximum length, in Unicode scalar values, of a project's
 * `## Current State` section body. `0` disables the check.
 *
 * Current State is a *snapshot*, not a running narrative: every
 * update auto-logs the previous body to the daily note, so the
 * long-form history is preserved there regardless. Agent-driven
 * updates tend to sprawl past that intent, so the cap keeps the
 * field terse. What happens on breach is governed by
 * [`state_overflow`](Self::state_overflow).
 */
max_state_chars: number, 
/**
 * What [`update_project_state`] does when a new Current State
 * exceeds [`max_state_chars`](Self::max_state_chars).
 *
 * [`update_project_state`]: ../../cdno_domain/vault/struct.Vault.html
 */
state_overflow: StateOverflow, };
