// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";
import type { VaultArea } from "./VaultArea";

export type VaultChanged = { origin: Origin, areas: Array<VaultArea>, paths: Array<string>, };
