// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse buckets the frontend maps to query-key prefixes. One area
 * per top-level vault directory, split where the journal folds two
 * note types into one tree.
 */
export type VaultArea = "projects" | "actions" | "daily" | "weekly" | "monthly" | "commitments" | "portfolios" | "stewardships" | "questions" | "inbox" | "config";
