// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `[vault]` section — basic vault metadata.
 */
export type VaultMeta = { name: string, max_active_projects: number, };
