// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The writable sections of the weekly note, parsed from an existing
 * note (or all `None` when the week has no note yet). `None` also
 * stands in for a present-but-empty section — the scaffold seeds four
 * empty sections, and an empty section must not beat a fresh seed, so
 * the frontend treats "empty" and "absent" identically.
 */
export type WeeklyContent = { 
/**
 * Whether a note file exists for the week at all — distinguishes a
 * never-started review from one whose sections are simply empty.
 */
exists: boolean, wins: string | null, challenges: string | null, one_improvement: string | null, this_weeks_goal: string | null, };
