// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentEntry } from "./CommitmentEntry";
import type { CompletedActionView } from "./CompletedActionView";
import type { ProjectSummary } from "./ProjectSummary";
import type { StewardshipSummary } from "./StewardshipSummary";
import type { StuckProject } from "./StuckProject";
import type { WeeklyContent } from "./WeeklyContent";
import type { WeeklyLogLine } from "./WeeklyLogLine";

/**
 * The composed Weekly Review data (plan §1.4). One read, every panel:
 * the resolved week anchor (and the following week's, for the focus
 * save), the existing note's sections, next week's goal, the wins-seed
 * sources, the project and stewardship scans, the stuck set, and the
 * commitments lookahead (14 days forward plus the overdue look-back).
 */
export type WeeklyBundle = { 
/**
 * The Monday of the reviewed ISO week — a stable identity the
 * frontend labels the week with and echoes back into
 * `save_weekly_section`. Any day in the week resolves here.
 */
week_of: string, 
/**
 * The Monday of the week *after* the reviewed one. The Focus step's
 * "next week's focus" belongs to next week's note (weekly.rs: the
 * goal is "carried into the next week's note by the review"), not
 * the week under review — so the frontend echoes this back into
 * `save_weekly_section` for the focus save. Exposed here so the
 * frontend never does date arithmetic (plan §3.7).
 */
next_week_of: string, 
/**
 * The real current date the lookahead was computed against
 * (stamped in Rust, like `CommitmentsView.today`), so the shared
 * timeline can label months and split past/upcoming without
 * touching a clock.
 */
today: string, 
/**
 * The weekly note's existing section content, so step 1 (Wins) can
 * prefer what's already written over the seed.
 */
weekly: WeeklyContent, 
/**
 * Next week's existing goal, read from the note at `next_week_of`
 * (`None` when that note doesn't exist yet or its goal section is
 * empty). The Focus step seeds from this so it edits an
 * already-planned goal rather than blindly overwriting it — and
 * crucially reads NEXT week's goal, not the reviewed week's.
 */
next_week_goal: string | null, 
/**
 * Action notes completed within the reviewed week — the primary
 * wins-seed source ("Completed: {title} ({project})").
 */
completed_actions: Array<CompletedActionView>, 
/**
 * The week's daily-log lines (capped), the secondary wins-seed
 * source and a memory jog for "what felt like progress anyway?".
 */
logs: Array<WeeklyLogLine>, 
/**
 * Active projects, each with its context and current-state snippet,
 * for the step-2 inline scan. `context` rides along in the summary.
 */
projects: Array<ProjectSummary>, 
/**
 * Active projects whose map has sat untouched past the staleness
 * threshold, paired with how many days — the grey step-2 hint.
 */
stuck: Array<StuckProject>, 
/**
 * Dated commitments for the step-4 lookahead: the next 14 days
 * forward, plus anything overdue within the domain's 30-day
 * look-back (the `commitments` query folds both together, so this
 * is not purely forward-looking).
 */
commitments: Array<CommitmentEntry>, 
/**
 * Every stewardship with its tracking count and staleness, for the
 * read-only step-3 scan.
 */
stewardships: Array<StewardshipSummary>, };
