// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One daily-log line in the reviewed week, flattened from the domain
 * `DailyLogLine` (which carries no serialisation derives). Mirrors
 * `projects.rs`'s `LogMentionView`.
 */
export type WeeklyLogLine = { date: string, time: string, text: string, };
