// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitmentEntry } from "./CommitmentEntry";
import type { CompletedActionView } from "./CompletedActionView";
import type { ProjectSummary } from "./ProjectSummary";
import type { StewardshipSummary } from "./StewardshipSummary";
import type { StuckProject } from "./StuckProject";
import type { WeeklyContent } from "./WeeklyContent";
import type { WeeklyLogLine } from "./WeeklyLogLine";

/**
 * The composed Weekly Review data (plan §1.4). One read, every panel:
 * the resolved week anchor, the existing note's sections, the wins-seed
 * sources, the project and stewardship scans, the stuck set, and the
 * 14-day commitments lookahead.
 */
export type WeeklyBundle = { 
/**
 * The Monday of the reviewed ISO week — a stable identity the
 * frontend labels the week with and echoes back into
 * `save_weekly_section`. Any day in the week resolves here.
 */
week_of: string, 
/**
 * The real current date the lookahead was computed against
 * (stamped in Rust, like `CommitmentsView.today`), so the shared
 * timeline can label months and split past/upcoming without
 * touching a clock.
 */
today: string, 
/**
 * The weekly note's existing section content, so step 1 (Wins) and
 * step 5 (Focus) can prefer what's already written over the seed.
 */
weekly: WeeklyContent, 
/**
 * Action notes completed within the reviewed week — the primary
 * wins-seed source ("Completed: {title} ({project})").
 */
completed_actions: Array<CompletedActionView>, 
/**
 * The week's daily-log lines (capped), the secondary wins-seed
 * source and a memory jog for "what felt like progress anyway?".
 */
logs: Array<WeeklyLogLine>, 
/**
 * Active projects, each with its context and current-state snippet,
 * for the step-2 inline scan. `context` rides along in the summary.
 */
projects: Array<ProjectSummary>, 
/**
 * Active projects whose map has sat untouched past the staleness
 * threshold, paired with how many days — the grey step-2 hint.
 */
stuck: Array<StuckProject>, 
/**
 * The next 14 days of dated commitments, for the step-4 lookahead.
 */
commitments: Array<CommitmentEntry>, 
/**
 * Every stewardship with its tracking count and staleness, for the
 * read-only step-3 scan.
 */
stewardships: Array<StewardshipSummary>, };
