// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A weekly note's raw content for the calendar panel's week jump.
 * Distinct from the composed `WeeklyBundle` (which stitches the guided
 * review): this is the note itself, absence-tolerant like `DailyView`.
 */
export type WeeklyView = { 
/**
 * The Monday of the ISO week the note covers, echoed back.
 */
week_of: string, exists: boolean, markdown: string, 
/**
 * The note's vault-relative path (resolved even when absent, for
 * "Open in editor").
 */
path: string, };
